### ISSUE TITLE
use countrycode package for all code conversions

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSpatialUtils#2]
Importing this package will make it easier for others to contribute new convert~() functions.

**Comment by tbergama** [comment]
@jonathancallahan 
It looks like the countrycode::countrycode() function can replace:
* iso2ToIso3()
* iso3ToIso2()
* codeToCountry()
* countryToCode()
\n
A quick fix would be to have the above functions wrap countrycode::countrycode() instead of replacing each usage of the above functions. What do you think?
